---
- become: yes
  block:
  - name: Copy /etc/blackbox_exporter/config.yml
    copy:
      src: "{{ blackbox_exporter.config_path }}"
      dest: /etc/blackbox_exporter/config.yml

  - name: Read file content
    ansible.builtin.shell: cat /etc/blackbox_exporter/config.yml
    register: file_content

  - name: Print file content
    ansible.builtin.debug:
      msg: "{{ file_content.stdout }}"