---
- become: yes
  block:

  - name: Create /etc/blackbox_exporter directory
    file:
      path: /etc/blackbox_exporter
      state: directory

  - name: Create /etc/blackbox_exporter/config.yml from template {{ blackbox_exporter.config_template_path }}
    template:
      src: "{{ blackbox_exporter.config_template_path }}"
      dest: /etc/blackbox_exporter/config.yml
    notify: 
    - Restart Blackbox Exporter

  - name: Run Blackbox Exporter container
    community.docker.docker_container:
      name: blackbox-exporter
      image: "{{ blackbox_exporter.docker_image }}"
      state: started
      restart_policy: always
      volumes:
      - "/etc/blackbox_exporter:/etc/blackbox_exporter"
      ports:
      - "{{ blackbox_exporter.container_port }}:{{ blackbox_exporter.port }}"
    notify: 
    - Restart Blackbox Exporter