---
- become: yes
  block:
  - name: Copy /etc/blackbox_exporter/config.yml
    copy:
      src: "{{ blackbox_exporter.config_path }}"
      dest: /etc/blackbox_exporter/config.yml

  - name: Run Blackbox Exporter container
    community.docker.docker_container:
      name: blackbox-exporter
      image: quay.io/prometheus/blackbox-exporter:v0.24.0
      state: started
      restart_policy: always
      volumes:
        - "/etc/blackbox_exporter:/etc/blackbox_exporter"
      ports:
        - "{{ blackbox_exporter.port }}:9115"