---
- name: Converge
  hosts: all
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml
    - vars.yml
  tasks:
    - name: Include the required roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - common
        - docker

    - name: "Include test role"
      ansible.builtin.include_role:
        name: Common.BlackboxExporter
