---
roles: 
- src: git+ssh://git@gitlab.avant-it.ru/main/common/ansibleroles/common.common.git
  scm: git
  version: 1.11.2
  name: common
- src: git+ssh://git@gitlab.avant-it.ru/main/common/ansibleroles/common.ansiblecontroller.git
  scm: git
  version: 2.0.5
  name: ansible-controller
- src: git+ssh://git@gitlab.avant-it.ru/main/common/ansibleroles/common.docker.git
  scm: git
  version: 2.7.4
  name: docker
