---
- name: Verify Blackbox Exporter Installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure Blackbox Exporter binary is installed
      ansible.builtin.command:
        cmd: blackbox_exporter --version
      register: blackbox_version
      failed_when: "'Blackbox Exporter' not in blackbox_version.stdout"

    - name: Ensure configuration file exists
      ansible.builtin.stat:
        path: /etc/blackbox_exporter/blackbox.yml
      register: config_file

    - name: Ensure Blackbox Exporter port 9115 is listening
      ansible.builtin.command:
        cmd: netstat -tuln | grep ':9115 '
      register: port_check
      failed_when: port_check.rc != 0

    - name: Ensure Blackbox Exporter metrics endpoint is reachable
      ansible.builtin.uri:
        url: http://localhost:9115/metrics
        method: GET
        status_code: 200
      register: metrics_endpoint

    - name: Fail if metrics endpoint is not available
      ansible.builtin.fail:
        msg: "Metrics endpoint is not reachable"
      when: metrics_endpoint.status != 200
