---
- name: Verify Blackbox Exporter Installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure configuration file exists
      ansible.builtin.stat:
        path: /etc/blackbox_exporter/config.yml
      register: config_file

    - name: Get container info
      community.docker.docker_container_info:
        name: backbox-exporter
      register: container_info

    - name: Fail if container is not running
      fail:
        msg: "Container 'backbox-exporter' is not running!"
      when: not container_info.exists or container_info.container.State.Running == false

    - name: Ensure Blackbox Exporter port 9115 is listening
      ansible.builtin.command:
        cmd: netstat -tuln | grep ':9115 '
      register: port_check
      failed_when: port_check.rc != 0

    - name: Ensure Blackbox Exporter metrics endpoint is reachable
      ansible.builtin.uri:
        url: http://localhost:9115/metrics
        method: GET
        status_code: 200
      register: metrics_endpoint

    - name: Fail if metrics endpoint is not available
      ansible.builtin.fail:
        msg: "Metrics endpoint is not reachable"
      when: metrics_endpoint.status != 200
